name: 'edu_sharing_com'
version: '0.1'
profile: 'edu_sharing_com'
config-version: 2
require-dbt-version: ">=0.21.0"

source-paths: [ "models" ]
analysis-paths: [ "analysis" ]
test-paths: [ "tests" ]
data-paths: [ "seeds" ]
macro-paths: [ "macros" ]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  edu_sharing_com:
    staging:
      +full_refresh: true
      materialized: table

seeds:
  edu_sharing_com:
    +schema: raw
    +full_refresh: true
    +quote_columns: false
