version: "3.8"

networks:
  default:
    external: true
    name: core_backend

services:

  dbt:
    build: ./
    image: community.docker.edu-sharing.com/dbt:latest
    container_name: dbt
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=analytics
    ports:
      - "8580:8580"
    volumes:
      - ./:/dbt
    command: [ "dbt", "rpc" ]

#  dbt-docs:
#    image: community.docker.edu-sharing.com/dbt:latest
#    container_name: dbt-docs
#    environment:
#      - POSTGRES_HOST=postgres
#      - POSTGRES_PORT=5432
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=analytics
#    volumes:
#      - ./:/dbt
#    entrypoint:
#      - /bin/sh
#      - -c
#    command:
#      - dbt docs generate && dbt docs serve
