version: 2

models:

  - name: collections
#    description: <markdown_string>
    config: {}
    columns:
      - name: id
        data_type: uuid
      - name: path
        data_type: ltree
      - name: cm__title
        data_type: text
      - name: cm__title
        data_type: text
      - name: ccm__taxonid
        data_type: jsonb
      - name: ccm__educationalcontext
        data_type: jsonb
      - name: cm__description
        data_type: text
      - name: ccm__general_keyword
        data_type: jsonb
      - name: parent_id
        data_type: uuid
      - name: portal_id
        data_type: uuid
      - name: portal_path
        data_type: ltree
      - name: portal_depth
        data_type: integer
      - name: spellcheck_lang
        data_type: text
      - name: portal_title
        data_type: text

  - name: materials
    #    description: <markdown_string>
    config: {}
    columns:
      - name: id
        data_type: uuid
      - name: cclom__title
        data_type: text
      - name: ccm__objecttype
        data_type: text
      - name: ccm__taxonid
        data_type: jsonb
      - name: ccm__educationalcontext
        data_type: jsonb
      - name: ccm__educationallearningresourcetype
        data_type: jsonb
      - name: ccm__educationalintendedenduserrole
        data_type: jsonb
      - name: cclom__general_description
        data_type: jsonb
      - name: cclom__general_keyword
        data_type: jsonb
      - name: ccm__commonlicense_key
        data_type: jsonb
      - name: ccm__oeh_languageLevel
        data_type: jsonb
      - name: ccm__wwwurl
        data_type: text
      - name: ccm__oeh_widgets
        data_type: jsonb
      - name: ccm__replicationsource
        data_type: text
      - name: ccm__replicationsourceid
        data_type: text
      - name: cm__created
        data_type: timestamp
      - name: cm__modified
        data_type: timestamp
      - name: created_at
        data_type: timestamp

  - name: collection_material
    #    description: <markdown_string>
    config: {}
    columns:
      - name: portal_title
        data_type: text
      - name: portal_id
        data_type: uuid
      - name: material_id
        data_type: uuid
